import type { Metadata } from "next";
import "./globals.css";
import { cn, font } from "@/lib/utils";
import Footer from "@/components/Footer";
import Provider from "./provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(font.className, "bg-primary")}>
        <Provider>
          <div className="min-h-screen">{children}</div>
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
