import type { Metadata } from "next";
import "./globals.css";
import { cn, font } from "@/lib/utils";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(font.className, "bg-primary")}>
        <Toaster richColors={true} position="top-center" />
        <div className="min-h-screen px-3 py-20 xl:py-0">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
